version: "3.9"

services:
  app:
    build: .
    container_name: stock-tracker
    image: tracker
    # env_file:
    #   - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
    command: python manage.py runserver 0.0.0.0:8000
